### ISSUE TITLE
Невегетарианским блюдо может сделать не только мясо

### ISSUE THREAD

**Issue by uzarsalan** [OlegB-e/HomeWork8#1]
https://github.com/OlegB-e/HomeWork8/blob/a1fdc82257118af5cfb77779ceb87abb70a88ae3/script.js#L53

Может быть несколько ингредиентов, которые делают блюдо не вегетарианским

**Comment by OlegB-e** [comment]
Добавил больше не вегетарианских ингредиентов.

**Comment by uzarsalan** [comment]
@OlegB-e это неудобно, добавлять новый ингредиент сразу в нескольких местах. Удобнее было добавлять их в одном месте. На самом деле я думаю невегетарианских ингредиентов тысячи

**Comment by OlegB-e** [comment]
Тогда стоит создать массив с вегетарианскими ингредиентами?
`const vegetarianIngredients = ['dough', 'onions', 'potato', 'pepperoni', 'tomatoes', 'cheese', 'cucumbers'];`

**Comment by uzarsalan** [comment]
Проще наверное сделать массив с НЕвегетарианскими ингредиентами

С уважением, Арсалан Рабданов!


Ср, 8 мая 2024 г. в 17:17, Oleg ***@***.***>:

**Comment by OlegB-e** [comment]
Точно! Спасибо за подсказку :D

**Comment by uzarsalan** [comment]
Потому что из меньше обычно. А вот веганских очень много. Включая разные
соусы, приправы и т.п.

С уважением, Арсалан Рабданов!


Ср, 8 мая 2024 г. в 17:17, Oleg ***@***.***>:

**Comment by OlegB-e** [comment]
Буду учитывать это в будущем, спасибо, буду сейчас улучшать код.

**Comment by OlegB-e** [comment]
Добрый день, проверьте изменения.

**Comment by OlegB-e** [comment]
Добрый день, проверьте изменение.

**Comment by uzarsalan** [comment]
Будет удобнее, если будешь сюда прикреплять ссылку на коммит

**Comment by OlegB-e** [comment]
Блин, я изменил прямо в git в ветке main, лучше менять через visual studio code?
https://github.com/OlegB-e/HomeWork8/blob/7706261463b7e279f82bb716f0bc77ee79c04fe1/script.js#L31

Все, вроде разобрался как вставлять строки.

**Comment by uzarsalan** [comment]
Да, лучше в vscode и в отдельной ветке
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue

**Comment by OlegB-e** [comment]
Хорошо
